# Generated by Django 5.1.2 on 2024-10-11 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_description_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='prompt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
