# Generated by Django 5.1.2 on 2024-10-11 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_image_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='has_been_described',
            field=models.BooleanField(default=False),
        ),
    ]
